email: hi@futureofindustry.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


theme: minima
plugins:
  - jekyll-feed

google_analytics: G-JLKGTPD7FY
twitter_username: futureofindustry 
rss: true